repos:
  - repo: local
    hooks:
      - id: golangci-lint
        name: golangci-lint
        description: |
          Same as golangci-lint's official hook, but works with multiple Go modules.
          https://github.com/golangci/golangci-lint/blob/main/.pre-commit-hooks.yaml
        entry: "task pre-commit:golangci-lint -- "
        language: system
        pass_filenames: true
        types: [go]
