---
name: stale

on:
  schedule:
    # Run weekly on Saturdays
    - cron: "30 1 * * 6"
  # Run the workflow manually
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write

jobs:
  mark-stale:
    name: Mark stale items
    runs-on: ubuntu-latest
    steps:
      - name: Mark stale issues and pull requests
        uses: actions/stale@1e223db275d687790206a7acac4d1a11bd6fe629 # v10.4.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          days-before-stale: 60
          days-before-close: 7
          stale-issue-label: stale
          stale-pr-label: stale
          exempt-issue-labels: keep
          exempt-pr-labels: keep
